# Generated by Django 4.2.7 on 2023-11-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_auto_20161020_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kirrurl',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
