# Generated by Django 4.2.7 on 2023-11-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickevent',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
